apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  labels:
    app: midterm-app
    role: migration

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: midterm-app
        role: migration

    spec:
      restartPolicy: Never

      volumes:
      - name: migrations
        configMap:
          name: migrations

      containers:
      - name: migration
        image: migration-app:1.0
        imagePullPolicy: Never

        command: ["./built-binary", "up"]

        args:
        - -driver=postgres
        - -url=postgres://postgres:postgres@postgres-service:5432/basic?sslmode=disable&connect_timeout=5
        - -path=/migrations/0001_up_database.up.sql

        volumeMounts:
        - name: migrations
          mountPath: /migrations
          readOnly: true

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"