apiVersion: v1
kind: Pod
metadata:
  name: lab5

spec:
  automountServiceAccountToken: false     # ← this is the missing piece

  securityContext:
    fsGroup: 2000

  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault

    resources: {}