apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
    - name: pgdata
      emptyDir: {}  # for demo; in prod, use a PersistentVolumeClaim

  initContainers:
  - name: fix-permissions
    image: busybox
    command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
    volumeMounts:
    - name: pgdata
      mountPath: /var/lib/postgresql/data

  securityContext:
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: database
      image: postgres:16-alpine
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "basic"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      securityContext:
        runAsUser: 999
        runAsGroup: 999
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false

      readinessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 2
        
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 15

      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
