apiVersion: v1
kind: Pod
metadata:
  name: lab3-test
  labels:
    app: lab3-app

spec:
  volumes:
  - name: app-config
    configMap:
      name: app-config   # ← IMPORTANT

  containers:

  - name: database
    image: postgres:16-alpine
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_DB
      value: "basic"
    ports:
    - name: pg-port
      containerPort: 5432
    resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

  - name: application
    image: golang-app:1.1
    imagePullPolicy: Never
    ports:
    - name: http-port
      containerPort: 8080

    volumeMounts:
    - name: app-config
      mountPath: /etc/config
      readOnly: true
    resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"